### ISSUE TITLE
R710 Supported

### ISSUE THREAD

**Issue by Quantas** [kamermans/docker-openmanage#5]
I was able to test this image successfully on my R710 :)

**Comment by Quantas** [comment]
Whoops, I tested the "Dell" image, not this one, I will test this one tonight.

**Comment by Quantas** [comment]
Ok, I was able to run your image, here are my details:

Dell r710 with PERC 6/i
OS: Proxmox 5.0 (Debian Stretch)

Added Docker to Host OS
Added Image
Successfully login to OMSA web UI
Successfully listed out updates with DSU but did not apply any at this time

**Comment by kamermans** [comment]
Great, thanks!

**Comment by Quantas** [comment]
Just tested on a second r710 and did a firmware update on an H700 RAID controller :)

**Comment by kamermans** [comment]
Thanks, I've also tested it on the H700 and 6i with other servers.
