### ISSUE TITLE
update dsu 1.5.3

### ISSUE THREAD

**Issue by chasebolt** [kamermans/docker-openmanage#6]
awesome work on this container! any chance you can rebuild this image on dockerhub to pull in dsu 1.5.3?

**Comment by kamermans** [comment]
Thanks!  I've rebuilt it and pushed it:
```
$ docker run --rm kamermans/docker-openmanage:latest dsu --version
DELL EMC System Update 1.5.3
Copyright (C) 2014 DELL EMC Proprietary.
```

Have a good weekend!

**Comment by chasebolt** [comment]
awesome thanks a lot!
