### ISSUE TITLE
Docker hub image needs a rebuild

### ISSUE THREAD

**Issue by shane-axiom** [kamermans/docker-openmanage#8]
I'm getting the following on multiple servers when running `dsu` in `kamermans/docker-openmanage:latest` on Docker hub:

```
Getting System Inventory ...
Inventory file not found - /usr/libexec/dell_dup/inv.xml
Exiting DSU!
```

However, if I run `yum update` inside the image first and then `dsu` it seems to work, suggesting that the `latest` image on Docker hub just needs to be rebuilt to pull in newer versions of packages.

**Comment by kamermans** [comment]
I've updated the image on Docker Hub after troubleshooting some missing log file issues.  Please let me know if this solves your problem!

**Comment by shane-axiom** [comment]
@kamermans Thanks, this fixed the issue!
