### ISSUE TITLE
Can't start srvadmin services on latest build

### ISSUE THREAD

**Issue by shane-axiom** [kamermans/docker-openmanage#9]
I haven't dug deep into this yet, but there appears to be a regression on the `latest` build. I notivced when no controllers were detected by `omreport storage controller`. It looks like the srvadmin services can't be started in `latest` but work fine in `dsu-1.5.3`:

```
$ sudo docker run --rm -ti --privileged --net=host -v /dev:/dev kamermans/docker-openmanage:latest bash -c "srvadmin-services.sh status"
#exits immediately with no output
$ sudo docker run --rm -ti --privileged --net=host -v /dev:/dev kamermans/docker-openmanage:dsu-1.5.3 bash -c "srvadmin-services.sh status"
dell_rbu (module) is running
ipmi driver is running
dsm_sa_datamgrd is stopped
dsm_sa_eventmgrd is stopped
dsm_sa_snmpd is stopped
dsm_om_connsvcd is stopped
```

On `dsu-1.5.3` I can use `srvadmin-services.sh status` to start the other services (e.g. `dsm_sa_datamgrd`), on `latest` nothing happens.

**Comment by shane-axiom** [comment]
I don't see any git tags on the repo so I can't be sure when `dsu-1.5.3` was built, but I assume this is the only commit on `latest` that's not in `dsu-1.5.3`, which is...odd.

https://github.com/kamermans/docker-openmanage/commit/ecc1194dc568f6ca8e9af44898d05ddc6b900015

**Comment by shane-axiom** [comment]
`yum -y update` appears to break a previously working `dsu-1.5.3` container.

**Comment by kamermans** [comment]
Hi @shane-axiom - I rebuilt the image recently, but I don't think there were any changes to the `Dockerfile` since it was just a matter of new `yum` updates.  I can try to pin things back if we can figure out what is breaking a find the most recent working version of it.

**Comment by kamermans** [comment]
Ok, I've found the problem.  In the new version of `srvadmin` (`9.2.0`, previously `9.1.0`), the start scripts use `systemd`, where they used to use `sysV/init.d` scripts.  Using `systemd` in a docker container is not trivial - I'll explore some options.

**Comment by shane-axiom** [comment]
Ouch, nice find though. Would it make sense to pin srvadmin to 9.1.0 until
a solution is found for the new version so that yum updates don’t break
things?

**Comment by kamermans** [comment]
I should probably pin everything since it's so hard to rebuild this image to a known state :)
